FROM node:20-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
COPY apps/scheduler/package.json ./apps/scheduler/
COPY packages/*/package.json ./packages/

RUN pnpm install --frozen-lockfile

COPY . .

WORKDIR /app/apps/scheduler

CMD ["npm", "run", "dev"]